src/app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from student.views import students_list, generate_students, students_add, students_edit, students_delete
from group.views import groups_list, generate_groups, groups_add, groups_edit, groups_delete
from teacher.views import teachers_list, generate_teachers, teachers_add, teachers_edit, teachers_delete

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name='admin-panel'),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('success/', TemplateView.as_view(template_name='success.html'), name='success'),

    path('account/', include('user_account.urls')),

    # path('students/', students_list, name='students'),
    # path('students-gen/', generate_students, name='students-gen'),
    # path('students/add/', students_add, name='students-add'),
    # path('students/edit/<int:id>', students_edit, name='students-edit'),
    # path('students/delete/<int:id>', students_delete, name='students-delete'),
    path('students/', include('student.urls')),
    # path('students/', include(('student.urls', 'students'))),


    # path('groups/', groups_list, name='groups'),
    # path('groups-gen/', generate_groups, name='groups-gen'),
    # path('groups/add/', groups_add, name='groups-add'),
    # path('groups/edit/<int:id>', groups_edit, name='groups-edit'),
    # path('groups/delete/<int:id>', groups_delete, name='groups-delete'),
    path('groups/', include('group.urls')),

    # path('teachers/', teachers_list, name='teachers'),
    # path('teacher-gen/', generate_teachers, name='teachers-gen'),
    # path('teachers/add/', teachers_add, name='teachers-add'),
    # path('teachers/edit/<int:id>', teachers_edit, name='teachers-edit'),
    # path('teachers/delete/<int:id>', teachers_delete, name='teachers-delete'),
    path('teachers/', include('teacher.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/group/urls.py
from django.urls import path

from group.views import groups_list, generate_groups, groups_add, groups_edit, groups_delete, GroupsListView, \
    GroupsUpdateView, GroupsCreateView, GroupsDeleteView

app_name = 'groups'

urlpatterns = [
    # path('', groups_list, name='list'),
    path('', GroupsListView.as_view(), name='list'),

    path('gen/', generate_groups, name='gen'),

    # path('add/', groups_add, name='add'),
    path('add/', GroupsCreateView.as_view(), name='add'),

    # path('edit/<int:id>', groups_edit, name='edit'),
    path('edit/<int:pk>', GroupsUpdateView.as_view(), name='edit'),

    # path('delete/<int:id>', groups_delete, name='delete'),
    path('delete/<int:pk>', GroupsDeleteView.as_view(), name='delete'),
]

src/student/urls.py
from django.urls import path

from student.views import students_list, generate_students, students_add, students_edit, students_delete, \
    StudentsListView, StudentsUpdateView, StudentsCreateView, StudentsDeleteView

app_name = 'students'

urlpatterns = [
    # path('', students_list, name='list'),
    # path('', MyView.as_view(), name='list'),
    path('', StudentsListView.as_view(), name='list'),

    path('gen/', generate_students, name='gen'),

    # path('add/', students_add, name='add'),
    path('add/', StudentsCreateView.as_view(), name='add'),

    # path('edit/<int:id>', students_edit, name='edit'),
    path('edit/<int:pk>', StudentsUpdateView.as_view(), name='edit'),

    # path('delete/<int:id>', students_delete, name='delete'),
    path('delete/<int:pk>', StudentsDeleteView.as_view(), name='delete'),
]

src/teacher/urls.py
from django.urls import path

from teacher.views import teachers_list, generate_teachers, teachers_add, teachers_edit, teachers_delete, \
    TeachersListView, TeachersCreateView, TeachersUpdateView, TeachersDeleteView

app_name = 'teachers'

urlpatterns = [
    # path('', teachers_list, name='list'),
    path('', TeachersListView.as_view(), name='list'),

    path('gen/', generate_teachers, name='gen'),

    # path('add/', teachers_add, name='add'),
    path('add/', TeachersCreateView.as_view(), name='add'),

    # path('edit/<int:id>', teachers_edit, name='edit'),
    path('edit/<int:pk>', TeachersUpdateView.as_view(), name='edit'),

    # path('delete/<int:id>', teachers_delete, name='delete'),
    path('delete/<int:pk>', TeachersDeleteView.as_view(), name='delete'),
]

src/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/base_1.css' %}">
<!--    <link rel="stylesheet" type="text/css" href="{% static 'user_account/css/base.css' %}">-->

</head>


<body>

<!--<h1>LMS</h1>-->

<!--    <a href="{% url 'students:list' %}">Students</a><br>-->
<!--    <a href="{% url 'teachers:list' %}">Teachers</a><br>-->
<!--    <a href="{% url 'groups:list' %}">Groups</a><br>-->

<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">


        <a class="navbar-brand" href="{% url 'index' %}">LMS</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'students:list' %}">Students <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:list' %}">Teachers</a>
                </li>
                <!--      <li class="nav-item dropdown">-->
                <!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
                <!--          Dropdown-->
                <!--        </a>-->
                <!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
                <!--          <a class="dropdown-item" href="#">Action</a>-->
                <!--          <a class="dropdown-item" href="#">Another action</a>-->
                <!--          <div class="dropdown-divider"></div>-->
                <!--          <a class="dropdown-item" href="#">Something else here</a>-->
                <!--        </div>-->
                <!--      </li>-->
                <!--      <li class="nav-item">-->
                <!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
                <!--      </li>-->
            </ul>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <img alt="Profile pic" width="40" height="40" class="rounded-circle" src="{{ user.profile.image.url }}">
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'profile' %}">Profile ({{ user.username}})</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'registration' %}">Register </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>

<!--            <form class="form-inline my-2 my-lg-0">-->
<!--                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--            </form>-->
        </div>
    </nav>
</div>


<div class="container">

        <div class="p-1 m-1">
            {% include 'includes/messages.html' %}
        </div>

<!--    <h2 class="p-4 mx-auto">{{ title }}</h2>-->
<!--    <p></p>-->
        <div class="border rounded text-center p-3 m-3 bg-light text-dark" >
            <h1>{% block title %}{{ title }}{% endblock %}</h1>
        </div>
<!--    {% if user.is_authenticated %}-->
<!--        LOGGED IN-->
<!--    {% else %}-->
<!--        NOT LOGGED IN-->
<!--    {% endif %}-->

    <p>
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </p>


    {% block  content %}

    {% endblock %}


<!--    <nav aria-label="pagination page">-->
<!--        <ul class="pagination justify-content-end pagination-sm">-->
<!--            {% if page_obj.has_previous %}-->
<!--                <li class="page-item">-->
<!--                    <a class="page-link" href="?page=1" aria-label="First">-->
<!--                        <span aria-hidden="true">&laquo; First</span>-->
<!--                        <span class="sr-only">First</span>-->
<!--                    </a>-->
<!--                <li class="page-item">-->
<!--                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">-->
<!--                        <span aria-hidden="true">&laquo; Previous</span>-->
<!--                        <span class="sr-only">Previous</span>-->
<!--                    </a>-->
<!--            {% endif %}-->

<!--             <li class="page-item active">-->
<!--                <span class="page-link">-->
<!--                    {{ page_obj.number }}-->
<!--                <span class="sr-only">(current)</span>-->
<!--                    </span>-->

<!--            {% if page_obj.has_next %}-->
<!--                <li class="page-item">-->
<!--                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">-->
<!--                        <span aria-hidden="true">Next &raquo;</span>-->
<!--                        <span class="sr-only">Next</span>-->
<!--                    </a>-->
<!--                <li class="page-item">-->
<!--                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">-->
<!--                        <span aria-hidden="true">Last &raquo;</span>-->
<!--                        <span class="sr-only">Last</span>-->
<!--                    </a>-->
<!--                {% endif %}-->

<!--        </ul>-->
<!--    </nav>-->


</div>

</body>

</html>

src/templates/index.html
{% extends 'base.html' %}


{% block title %}
    <div class="mx-auto" style="width: 400px;">
        <h1>Welcome to LMS!</h1>
    </div>
{% endblock %}

src/templates/index_0001.html
{% extends 'base.html' %}


{% block content %}

    <h1>Welcome to LMS</h1>

{% endblock %}

src/templates/success.html
{% extends 'base.html' %}

{% block content %}

    <h1>User successfully registered</h1>

    <a href="{% url 'index' %}" class="btn btn-light">Start page</a>

{% endblock %}