src/app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from student.views import students_list, generate_students, students_add, students_edit, students_delete
from group.views import groups_list, generate_groups, groups_add, groups_edit, groups_delete
from teacher.views import teachers_list, generate_teachers, teachers_add, teachers_edit, teachers_delete

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name='admin-panel'),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('success/', TemplateView.as_view(template_name='success.html'), name='success'),

    path('account/', include('user_account.urls')),

    # path('students/', students_list, name='students'),
    # path('students-gen/', generate_students, name='students-gen'),
    # path('students/add/', students_add, name='students-add'),
    # path('students/edit/<int:id>', students_edit, name='students-edit'),
    # path('students/delete/<int:id>', students_delete, name='students-delete'),
    path('students/', include('student.urls')),
    # path('students/', include(('student.urls', 'students'))),


    # path('groups/', groups_list, name='groups'),
    # path('groups-gen/', generate_groups, name='groups-gen'),
    # path('groups/add/', groups_add, name='groups-add'),
    # path('groups/edit/<int:id>', groups_edit, name='groups-edit'),
    # path('groups/delete/<int:id>', groups_delete, name='groups-delete'),
    path('groups/', include('group.urls')),

    # path('teachers/', teachers_list, name='teachers'),
    # path('teacher-gen/', generate_teachers, name='teachers-gen'),
    # path('teachers/add/', teachers_add, name='teachers-add'),
    # path('teachers/edit/<int:id>', teachers_edit, name='teachers-edit'),
    # path('teachers/delete/<int:id>', teachers_delete, name='teachers-delete'),
    path('teachers/', include('teacher.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/group/urls.py
from django.urls import path

from group.views import groups_list, generate_groups, groups_add, groups_edit, groups_delete, GroupsListView, \
    GroupsUpdateView, GroupsCreateView, GroupsDeleteView

app_name = 'groups'

urlpatterns = [
    # path('', groups_list, name='list'),
    path('', GroupsListView.as_view(), name='list'),

    path('gen/', generate_groups, name='gen'),

    # path('add/', groups_add, name='add'),
    path('add/', GroupsCreateView.as_view(), name='add'),

    # path('edit/<int:id>', groups_edit, name='edit'),
    path('edit/<int:pk>', GroupsUpdateView.as_view(), name='edit'),

    # path('delete/<int:id>', groups_delete, name='delete'),
    path('delete/<int:pk>', GroupsDeleteView.as_view(), name='delete'),
]

src/student/urls.py
from django.urls import path

from student.views import students_list, generate_students, students_add, students_edit, students_delete, \
    StudentsListView, StudentsUpdateView, StudentsCreateView, StudentsDeleteView

app_name = 'students'

urlpatterns = [
    # path('', students_list, name='list'),
    # path('', MyView.as_view(), name='list'),
    path('', StudentsListView.as_view(), name='list'),

    path('gen/', generate_students, name='gen'),

    # path('add/', students_add, name='add'),
    path('add/', StudentsCreateView.as_view(), name='add'),

    # path('edit/<int:id>', students_edit, name='edit'),
    path('edit/<int:pk>', StudentsUpdateView.as_view(), name='edit'),

    # path('delete/<int:id>', students_delete, name='delete'),
    path('delete/<int:pk>', StudentsDeleteView.as_view(), name='delete'),
]

src/teacher/urls.py
from django.urls import path

from teacher.views import teachers_list, generate_teachers, teachers_add, teachers_edit, teachers_delete, \
    TeachersListView, TeachersCreateView, TeachersUpdateView, TeachersDeleteView

app_name = 'teachers'

urlpatterns = [
    # path('', teachers_list, name='list'),
    path('', TeachersListView.as_view(), name='list'),

    path('gen/', generate_teachers, name='gen'),

    # path('add/', teachers_add, name='add'),
    path('add/', TeachersCreateView.as_view(), name='add'),

    # path('edit/<int:id>', teachers_edit, name='edit'),
    path('edit/<int:pk>', TeachersUpdateView.as_view(), name='edit'),

    # path('delete/<int:id>', teachers_delete, name='delete'),
    path('delete/<int:pk>', TeachersDeleteView.as_view(), name='delete'),
]

src/group/models.py
import random

from django.db import models

# Create your models here.
from teacher.models import Teacher


class Classroom(models.Model):
    name = models.CharField(max_length=64)
    floor = models.SmallIntegerField(null=True)
    # floor = models.SmallIntegerField(max_length=128, null=True)

    def __str__(self):
        return f'{self.name} - Floor #{self.floor}'

    @classmethod
    def generate_classroom(cls):

        classroom = cls(
            name=f'Classroom - {random.choice(range(5))}',
            floor=random.choice(range(5)),
        )

        classroom.save()


class Group(models.Model):
    name = models.CharField(max_length=64)
    course = models.CharField(max_length=128)
    teacher = models.ForeignKey(
        to=Teacher,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups'
    )
    classroom = models.ManyToManyField(
        to=Classroom,
        # null=True,
        related_name='groups'
    )

    def __str__(self):
        return f'{self.name} - {self.course}'

    @classmethod
    def generate_group(cls):

        group = cls(
            name=f'Group - {random.choice(range(5))}',
            course=random.choice([
                "IT 210: Web Application Development.",
                "IT 226: Enterprise Information Systems.",
                "IT 227: E-Commerce Technologies.",
                "IT 238: Networking and Client/Server Computing.",
                "IT 280: Internet Security.",
                "IT 295: IT-Based Application Project.",
                "IT 299: Graduate Seminar.",
            ])
        )

        group.save()

src/group/forms.py
from django.forms import ModelForm
from group.models import Group


class GroupBaseForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class GroupAddForm(GroupBaseForm):
    pass


class GroupEditForm(GroupBaseForm):
    pass


class GroupDeleteForm(GroupBaseForm):
    pass

src/group/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView, UpdateView, CreateView, DeleteView

from group.forms import GroupAddForm, GroupEditForm, GroupDeleteForm
from group.models import Group

# Create your views here.


def generate_groups(request, num=1):
    for _ in range(num):
        Group.generate_group()
    qs = Group.objects.all()
    new_groups = qs[len(qs) - num:]
    result = '<br>'.join(
        str(group)
        for group in new_groups
    )
    return HttpResponse(result)


def groups_list(request):
    qs = Group.objects.all()

    if request.GET.get('gname'):
        qs = qs.filter(name=request.GET.get('gname'))

    if request.GET.get('gcourse'):
        qs = qs.filter(course=request.GET.get('gcourse'))

    # if request.GET.get('gname') or request.GET.get('gcourse'):
    #     qs =qs.filter(
    #         Q(name=request.GET.get('gname')) | Q(
    #             course=request.GET.get('gcourse'))
    #         )

    # result = '<br>'.join(
    #     str(group)
    #     for group in qs
    # )
    # return HttpResponse(result)
    return render(
        request=request,
        template_name='groups_list.html',
        context={
            'groups_list': qs,
            'title': 'Groups list'
        }
    )


def groups_add(request):

    if request.method == 'POST':
        form = GroupAddForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:list'))
    else:
        form = GroupAddForm

    return render(
        request=request,
        template_name='groups_add.html',
        context={
            'form': form,
            'title': 'Groups add'
        }
    )


def groups_edit(request, id):
    try:
        group = Group.objects.get(id=id)
    except ObjectDoesNotExist:
        return HttpResponseNotFound(f'Group with id={id} doesn\'t exist')

    if request.method == 'POST':
        form = GroupEditForm(request.POST, instance=group)

        if form.is_valid():
            group = form.save()
            print(f'Grope has been saved: {group}')
            return HttpResponseRedirect(reverse('groups:list'))
    else:
        form = GroupEditForm(
            instance=group
        )

    return render(
        request=request,
        template_name='groups_edit.html',
        context={
            'form': form,
            'title': 'Group edit',
            'group': group
        }
    )


def groups_delete(request, id):
    try:
        group = Group.objects.get(id=id)
    except ObjectDoesNotExist:
        return HttpResponseNotFound(f'Group with id={id} doesn\'t exist')

    if request.method == 'POST':
        form = GroupDeleteForm(request.POST, instance=group)

        group.delete()
        if form.is_valid():
            return HttpResponseRedirect(reverse('groups:list'))
    else:
        form = GroupDeleteForm(
            instance=group
        )

    return render(
        request=request,
        template_name='groups_delete.html',
        context={
            'form': form,
            'title': 'Group delete',
        }
    )


class GroupsListView(LoginRequiredMixin, ListView):
    model = Group
    template_name = 'groups_list.html'
    context_object_name = 'groups_list'
    login_url = reverse_lazy('login')
    paginate_by = 3

    def get_queryset(self):
        request = self.request
        qs = super().get_queryset()
        qs = qs.order_by('-id')

        # if request.GET.get('gname'):
        #     qs = qs.filter(name=request.GET.get('gname'))
        #
        # if request.GET.get('gcourse'):
        #     qs = qs.filter(course=request.GET.get('gcourse'))

        if request.GET.get('gname') or request.GET.get('gcourse'):
            qs = qs.filter(Q(name=request.GET.get('gname')) | Q(
                course=request.GET.get('course')))

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Groups list'
        return context


class GroupsUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    template_name = 'groups_edit.html'
    form_class = GroupEditForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse('groups:list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Edit group'
        return context


class GroupsCreateView(LoginRequiredMixin, CreateView):
    model = Group
    template_name = 'groups_add.html'
    form_class = GroupAddForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse('groups:list')


class GroupsDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    template_name = 'groups_delete.html'
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse('groups:list')

src/group/templates/base_0001.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>

<h1>LMS</h1>
<h3>{{ title }}</h3>

    <a href="{% url 'students:list' %}">Students</a><br>
    <a href="{% url 'teachers:list' %}">Teachers</a><br>
    <a href="{% url 'groups:list' %}">Groups</a><br>

{% block  content %}
{% endblock %}

</body>
</html>

src/group/templates/groups_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <form method="post">
        {% csrf_token %}
<!--        {{ form.as_p }}-->
        {{ form|crispy }}

      <button type="submit" class="btn btn-primary">Create</button>
      <a href="{% url 'groups:list' %}" class="btn btn-light">Cancel</a>

    </form>

{% endblock %}

src/group/templates/groups_delete.html
{% extends 'base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
         <h3>
             Do u really want to delete group <b> {{ group.name }} {{ group.course }}</b>?
         </h3>
      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'groups:list' %}" class="btn btn-light">Cancel</a>
    </form>

{% endblock %}

src/group/templates/groups_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <form method="post">
        {% csrf_token %}
<!--        {{ form.as_p }}-->
        {{ form|crispy }}

      <button type="submit" class="btn btn-primary">Save</button>
      <a href="{% url 'groups:list' %}" class="btn btn-light">Cancel</a>

    </form>

<!--    {% for student in group.students.all %}-->
<!--        {{ student.id }}-->
<!--        <a href="/students/edit/{{ student.id }}">{{ student.first_name }} {{ student.last_name }}</a>-->
<!--        {{ student.email }}-->
<!--        {{ group.name }}-->
<!--        <a href="/students/delete/{{ student.id }}">Delete</a>-->
<!--        <br>-->
<!--    {% empty %}-->
<!--        <p>Sorry, list is empty</p>-->
<!--    {% endfor %}-->

    <p></p>
    <p></p>

    {% with students_list=group.students.all %}
        {% include 'includes/students_table.html' %}
    {% endwith %}

{% endblock %}

src/group/templates/groups_list.html
{% extends 'base.html' %}

{% block content %}

<!--    <form>-->
<!--      <label for="gname">Group name:</label><br>-->
<!--      <input type="text" id="gname" name="gname"><br>-->
<!--      <label for="gcourse">Group course:</label><br>-->
<!--      <input type="text" id="gcourse" name="gcourse">-->
<!--      <button type="submit">Search</button>-->
<!--    </form>-->

    <form>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Group name</span>
          </div>
          <input  name="gname" type="text" class="form-control" placeholder="Group name" aria-label="firstname" aria-describedby="basic-addon1">

          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Group course</span>
          </div>
          <input  name="gcourse" type="text" class="form-control" placeholder="Group course" aria-label="lastname" aria-describedby="basic-addon1">

          <button type="submit" class="btn btn-success">Search</button>
        </div>
    </form>



<!--    {% for group in group_list %}-->
<!--        {{ group.id }}-->
<!--        <a href="/groups/edit/{{ group.id }}">{{ group.name }} {{ group.course }}</a>-->
<!--        {{ group.classroom }}-->
<!--        <br>-->
<!--    {% empty %}-->
<!--        <p>Sorry, list is empty</p>-->
<!--    {% endfor %}-->

    {% include 'includes/groups_table.html' %}

{% endblock %}